import collections
print (abs.__doc__)
print("\n ****************************************************")
print (print.__doc__)
print("\n ****************************************************")
print(int.__doc__)
print("\n ****************************************************")
print(sorted.__doc__)
print("\n ****************************************************")
print(collections.Counter.__doc__)